### ISSUE TITLE
vlc paths for 64bit 

### ISSUE THREAD

**Issue by omgbox** [JiPaix/xdccJS#229]
**Describe the bug**
user installed 64bit VLC there is a difference in path which is under C:\Program Files (x86)\VideoLAN\VLC\vlc.exe

**To Reproduce**
install 64bit and check path

**Expected behavior**
global path maybe to include 64 and 32 paths for vlc and maybe mpv path 

**Screenshots**
![vlc](https://user-images.githubusercontent.com/11356775/127763236-be002f10-1c9a-4779-900c-ccb048f167b3.PNG)

**Context:**
 - OS: windows
 - Version: 64

**Additional context**
maybe include both 64 and 32 pathways for binary. optional to include mpv , allow user to save player pathway when saving profile.

**Comment by JiPaix** [comment]
xdccJS piping isn't exclusive to VLC. Pathway are to be managed on your end (usually directly by your OS). 
you'd either have to add VLC in your PATH config or put the whole path to the exe file:  

`xdccJS --host irc.server.net --bot "XDCC|BOT" --download 110 | "C:\Path\to\My\VLC.exe" -`

**Comment by JiPaix** [comment]
If you need help with that follows this guide:  https://www.architectryan.com/2018/03/17/add-to-the-path-on-windows-10/

**Comment by omgbox** [comment]
> If you need help with that follows this guide: https://www.architectryan.com/2018/03/17/add-to-the-path-on-windows-10/

I have correctly added binary to path, but it seems that VLC is still not picking anything from fd:// , what might I be doing wrong any advice. 
![Untitled](https://user-images.githubusercontent.com/11356775/127872946-b064ad07-472d-434b-8e23-16d4f6863430.png)

**Comment by JiPaix** [comment]
> I have correctly added binary to path, but it seems that VLC is still not picking anything from fd:// , what might I be doing wrong any advice.

Nothing's wrong on your end, it appears using pipes with the CLI was broken, I released [v4.2.7](https://github.com/JiPaix/xdccJS/releases/tag/v4.2.7) on [npmjs](https://www.npmjs.com/package/xdccjs) which fix this issue (along with #227).  

You just need to update xdccJS

**Comment by omgbox** [comment]
it appears there might be some issue with setting up profiles, it seems to save the profile but it does not detect it 
I have removed and reinstalled xdccjs with the same issue.  streaming now works on vlc. 
![Untitled](https://user-images.githubusercontent.com/11356775/127954425-b54d6a5f-523b-4470-9d7e-cbd58190c069.png)

**Comment by omgbox** [comment]
keep downloading file even if vlc socket is closed .  its not really important but would be nice as not to restart the same download.

![sockets](https://user-images.githubusercontent.com/11356775/127955246-4ee3515a-d5ac-453d-9a6d-c4b92a3e15e9.png)

**Comment by JiPaix** [comment]
I opened issue #238 and #239 to discuss this matter.
