### ISSUE TITLE
Profile saved but not detected

### ISSUE THREAD

**Issue by JiPaix** [JiPaix/xdccJS#238]
it appears there might be some issue with setting up profiles, it seems to save the profile but it does not detect it 
I have removed and reinstalled xdccjs with the same issue.  streaming now works on vlc. 
![Untitled](https://user-images.githubusercontent.com/11356775/127954425-b54d6a5f-523b-4470-9d7e-cbd58190c069.png)

_Originally posted by @omgbox in https://github.com/JiPaix/xdccJS/issues/229#issuecomment-891497195_

**Comment by omgbox** [comment]
windows 64 - installed node with nvm
node -v  / v16.6.0
npm -v / 7.19.1
xdccjs -V / 4.2.7

**Comment by JiPaix** [comment]
> windows 64 - installed node with nvm
> node -v / v16.6.0
> npm -v / 7.19.1
> xdccjs -V / 4.2.7

fixed with 4.2.8
