### ISSUE TITLE
Poll: Does xdccJS need a WEB-UI ?

### ISSUE THREAD

**Issue by JiPaix** [JiPaix/xdccJS#240]
> What's a weebwee?

It's a Web User Interface, by definition « _a control panel in a device presented to the user via the Web browser_ »

> but what for ?

command-line is so 70's, wouldn't you rather use xdccJS with a nice graphical interface you can interact with?

### Click to vote: 
[![](https://api.gh-polls.com/poll/01FC70YXBX9FSRMHBCZH1452YT/Yes)](https://api.gh-polls.com/poll/01FC70YXBX9FSRMHBCZH1452YT/Yes/vote)
[![](https://api.gh-polls.com/poll/01FC70YXBX9FSRMHBCZH1452YT/No)](https://api.gh-polls.com/poll/01FC70YXBX9FSRMHBCZH1452YT/No/vote)
[![](https://api.gh-polls.com/poll/01FC70YXBX9FSRMHBCZH1452YT/I%20don't%20care)](https://api.gh-polls.com/poll/01FC70YXBX9FSRMHBCZH1452YT/I%20don't%20care/vote)

**Comment by omgbox** [comment]
would be perfectly suited for anime users with video.js integration

**Comment by omgbox** [comment]
another interesting dcc irc web chat app, supports downloads
https://github.com/khlieng/dispatch
