### ISSUE TITLE
xdccJS shutting down instantly/after a few seconds

### ISSUE THREAD

**Issue by EtzBetz** [JiPaix/xdccJS#492]
**Describe the bug**
I used the example template from the readme page, changed the server address to `irc.freenode.net` and ran that, but node will just run for a second or two and then shut down without any info. I expect it to run all the time until I shut it down?
Am I supposed to do something different? Am I missing error messages anywhere? I also tried using the `irc-framework`s raw event but there nothing gets output as well. Is this also maybe not designed for continuous running?

**To Reproduce**
1. Use the template from the readme page
2. exchange the server url for e.g. freenode
3. change the 'ready' function to do a log
4. `node index.js`

**Expected behavior**
The server would run, do the log and then just stay alive.

**Context:**
 - OS: macOS Monterey
 - Version: 4.4.19

**Comment by JiPaix** [comment]
I am unable to reproduce this issue, i'm not getting disconnected.  
using `irc-framework` raw event is the right approach. 

### Q&A

> Is this also maybe not designed for continuous running
- The client stays connected until you call `xdcc.quit()` (or you lose connection to the server).
> I also tried using the irc-frameworks raw event but there nothing gets output as well
- The only instance the server's doesn't ouput anything is when its network is unreachable. Either because it's down (highly unlikely for freenode) or your network is blocking the connection (firewall?).
- You probably should also **listen to xdccJS `error` event, it output network related errors**

### Test setup
```js
const XDCC = require('xdccjs');

const xdcc = new XDCC.default({
  host: 'irc.freenode.net',
  port: 6667,
  chan: ['#welcome', '#fansub'],
  nickname: 'Leon',
  path: 'dowloads'
});

xdcc.on('error', console.log)

xdcc.irc.on('raw', (m) => {
  console.log(m.line);
});
```




### Results
welcome message + message of the day
```console
:*.freenode.net 001 Leon :Welcome to the freenode IRC Network Leon!~Leon@76.12.xxx.xxx

:*.freenode.net 372 Leon :  Thank you for using freenode!
:*.freenode.net 376 Leon :End of message of the day.
```

setting user's mode wRix to hide IP + join channels 
```console
:*.freenode.net 396 Leon freenode-rht.v31.ckjv0g.IP :is now your displayed host
:Leon!~Leon@freenode-rht.v31.ckjv0g.IP MODE Leon :+wRix

:Leon!~Leon@freenode-rht.v31.ckjv0g.IP JOIN #welcome * :ircbot
:*.freenode.net 366 Leon #welcome :End of /NAMES list.

:Leon!~Leon@freenode-rht.v31.ckjv0g.IP JOIN #fansub * :ircbot
:*.freenode.net 366 Leon #fansub :End of /NAMES list.
```
NickServ Messages
```console
:NickServ!services@services.freenode.net NOTICE Leon :This nickname is registered and protected.  If it is your
:NickServ!services@services.freenode.net NOTICE Leon :nick, type /msg NickServ IDENTIFY password.  Otherwise,

:NickServ!services@services.freenode.net NOTICE Leon :please choose a different nick.
:NickServ!services@services.freenode.net NOTICE Leon :If you do not change within 1 minute, I will change your nick.

:NickServ!services@services.freenode.net NOTICE Leon :Your nickname is now being changed to Guest10456
```

**Comment by EtzBetz** [comment]
Hey,
thanks for the fast answer. Okay, I can use your code. I wasn't aware that I had to use `xdcc.irc.on(...)`  instead of `xdcc.on(...)` for events of irc-framework.
Seems to work now, thanks.
