### ISSUE TITLE
Be able to provide a password for NickServ to authenticate with nickname

### ISSUE THREAD

**Issue by Jayy001** [JiPaix/xdccJS#504]
Firstly, thank you for making this! It was one of the few tools I could find that actually worked on all the servers I tested it on 😀

Some servers give a wait time before you can download, this has been sorted with the `--wait` time argument, however most servers will remove this waiting time if you identify with NickServ with a registered nickname (`/msg NickServ IDENTIFY <pass>`). Being able to provide xdccJS a password to do this would shave of the waiting time and would be extremely useful.

![image](https://user-images.githubusercontent.com/56607897/173154350-9fe7f646-8001-4f24-91c3-03ba19d0a30e.png)

**Comment by JiPaix** [comment]
Thanks a lot for using xdccJS and your feedback :100: 
`--nickserv` option's been added, and is available with `v4.5.28`

❌ `--nickserv my password` (password shouldn't contain spaces, `--nickname` is missing)
:heavy_check_mark: `--nickname ItsMe --nickserv my_password`
