### ISSUE TITLE
Download bandwidth throttling

### ISSUE THREAD

**Issue by Chaphasilor** [JiPaix/xdccJS#707]
**Is your feature request related to a problem? Please describe.**

I have an automated downloader running on my server that will start to download files whenever they're available. This can be at arbitrary times, but ends up choking my network for larger files. Since there is no way to cap the download speed, my only option is to stop the download and retry at a later time, or not stream any videos for the duration of the download.

**Describe the solution you'd like**

Ideally, I'd like to set the maximum download speed for a single or all jobs. This limit should be adjustable dynamically by calling something like `job.throttle(2048*1000)` in order to update the maximum download speed to 2 MB/s.

**Describe alternatives you've considered**

I've previously used solutions like `wondershaper`, but that limits the whole network adaptor and not just a single node program. I'm sure there would be ways to limit the network bandwidth of the node program using a secondary tool, but I think adding a download speed limit would be fitting for a downloader library like this.

**Additional context**

There are some packages on npm that can limit streams, like [speed-limiter](https://www.npmjs.com/package/speed-limiter) or [throttled-reader](https://www.npmjs.com/package/throttled-reader). However, I'm not sure if they will actually impact TCP's flow control, of if the download will use the same bandwidth, caching the data before sending it through the throttled stream.

Would love to discuss this with you!

**Comment by Chaphasilor** [comment]
Hey, thanks for the super quick release! I'm currently checking it out, and I'm wondering if I can simply update `xdccJS.irc.throttle` with a new value to change the throttle on-the-fly, or if this won't work as expected?

**Comment by JiPaix** [comment]
> Hey, thanks for the super quick release! I'm currently checking it out, and I'm wondering if I can simply update `xdccJS.irc.throttle` with a new value to change the throttle on-the-fly, or if this won't work as expected?

I haven't test this case, but in theory yes, the new value should be applied even mid-download

**Comment by Chaphasilor** [comment]
Okay, just tested it, but it seems like the throttling is not working at all, sadly. I can see the set bandwidth reflected in the progress bar in the command line, and it does seem to change when updating `xdccJS.irc.throttle`, but the actual download speed it not affected at all. Not even when providing the `throttle` option directly to the constructor and not modifying afterwards.

The file size increases much faster than the set throttle, and the download progress does not align with the progress shown in the command line. I tested it by downloading a video and checking how far ahead I could skip in the downloaded video already :(

**Comment by JiPaix** [comment]
I found out why, I had a misconception on how to do this.

The solution i found can't (unless i spend countless hours i don't have) change the bandwidth limit until the next download is fired.

**Comment by Chaphasilor** [comment]
I guess that's fine. Restarting XDCC downloads isn't always a good idea (due to rate limiting, etc.), but maybe I can add some wrapping code that cancels an active download and re-queues it at a later time...

The download limit is still global and not per-job, right? But I should be able to set a global limit, start a download, and then reset the global limit, right?

I'll check it out in the coming days, currently don't have access to a PC...

**Comment by JiPaix** [comment]
> The download limit is still global and not per-job, right? But I should be able to set a global limit, start a download, and then reset the global limit, right?

see v5.1.2

https://github.com/JiPaix/xdccJS/blob/7982f88c5465573caa7933117bea556e7645dedd/CHANGELOG.md?plain=1#L1-L15

**Comment by Chaphasilor** [comment]
okay, gave it another spin. it's working much better now, and the per-download throttling is nice. there are only a few minor issues for me:

- there seems to be no way to read out the current config? I was trying to implement the status page, that shows the currently configured throttle, but I found no way to access it on the `xdccJS` object
- the throttle value is actually in B/s, not kB/s (as it should be). This should be reflected in the documentation, as well as in the console output that is printed after calling `config()`:
  > throttling at 2 GiB/s
  
  is actually 2 MiB/s
- ~~the options for the `download()` method seem to be lacking some types, the method throws and error if `throttle` is not a number or undefined~~ can't reproduce this anymore

I'll try to leave this running for a bit and report any issues :)

**Comment by JiPaix** [comment]
update to `5.1.5` should fix all that

> here seems to be no way to read out the current config? I was trying to implement the status page, that shows the currently configured throttle, but I found no way to access it on the xdccJS object

```js
// define global throttle
xdccJS.config({ throttle: 5000 })
// start job with specific throttle value
const job = await xdccJS.download('bot', [1-5], { throttle: 1000 })

console.log(xdccJS.config().throttle) //=> 5000
console.log(job.show().throttle) //=> 1000
```

> the throttle value is actually in B/s, not kB/s (as it should be). This should be reflected in the documentation, as well as in the console output that is printed after calling config():

Fixed
